# spring.application.name=springRest

# #config database
# ###
# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=jdbc:mysql://localhost:3307/spring_boot_2
# spring.datasource.username=root
# spring.datasource.password=123456
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.show-sql: true
# ###

# #config upload file
# ###
# #default = 1MB
# spring.servlet.multipart.max-file-size=50MB  

# #default = 10 MB (form data)
# spring.servlet.multipart.max-request-size=50MB
# ###

spring:
  application:
    name: springRest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3307/spring_boot_2
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
# cấu hình jwt gồm, 2 tham số: secret key để mã hoá và thời gian hết hạn của token
hoidanit:
  jwt:
    base64-secret: MJ6i2JZpaUmX5IbEWGNKxlky+prUeUlrIX9Twxja9vkqr/3keOybYpFULyjdlnTM486FerKHXHjBeQcAWniZDA==
    token-validity-in-seconds: 86400
